source 'https://rubygems.byted.org'

gem 'cocoapods', '1.8.4'

gem "fastlane", '~> 2.198.1'

gem "cocoapods-packager", '~> 1.5.1'

gem "xcodeproj", '>= 1.21.0', '< 2.0'

gem "CFPropertyList", '3.0.5'

gem 'bd_pod_extentions', '6.4.1'