source 'https://rubygems.byted.org'

# required version 1.8.4 by plugin `cocoapods-bytedance-duplication`
gem 'cocoapods', '1.8.4'

gem 'bd_pod_extentions', '6.4.1'

gem "fastlane", '~> 2.198.1'

gem "cocoapods-packager",  '~> 1.5.1'

gem "xcodeproj", '1.19.0'

gem "CFPropertyList", '3.0.5'

gem 'rqrcode',  '2.1.0'

gem 'rqrcode_png', '0.1.5'

gem 'cocoapods-optimize', '2.1.24'
