source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/bytedance/cocoapods_sdk_source_repo.git'
source 'https://github.com/volcengine/volcengine-specs.git'

install! 'cocoapods', :deterministic_uuids => false

platform :ios, "8.0"

inhibit_all_warnings!

def ttsdk_pods
  pod 'TTSDK', '1.17.2.3-premium', :subspecs => [
    'Core',
    'TTFFmpeg',
    'PlayerCore',
    'LivePull',
    'LivePush',
    'Player',
    'Image',
    'Uploader',
  ]
end

def common_pods
  pod 'Masonry'
  pod 'ReactiveCocoa', '2.5'
  pod 'FLEX'
  pod 'Toast', '~> 4.0.0'
  pod 'YYCategories'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJExtension'
  pod 'IQKeyboardManager'
  pod 'RangersAppLog', '~> 5.3.1', :subspecs => ['Core']
  pod 'MWPhotoBrowser'
end

target 'TTSDKDemo' do
  ttsdk_pods
  common_pods
end

post_install do |installer|
  system("bash Scripts/update_git_info.sh")
end
