source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/bytedance/cocoapods_sdk_source_repo.git'
source 'https://github.com/volcengine/volcengine-specs.git'

install! 'cocoapods', :deterministic_uuids => false

platform :ios, "8.0"

inhibit_all_warnings!

target 'TTSDKDemo' do
  pod 'TTSDK',:subspecs => [
    'Core',
    'TTFFmpeg',
    'PlayerCore',
    'LivePull',
    'LivePush',
    'Player',
    'Image',
  ] ,:path=>'../'

  pod 'Masonry'
  pod 'ReactiveCocoa', '2.5'
  pod 'FLEX'
  pod 'Toast', '~> 4.0.0'
  pod 'YYCategories'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJExtension'
  pod 'IQKeyboardManager'
  pod 'CocoaAsyncSocket'
  pod 'RangersAppLog', '~> 5.3.1', :subspecs => ['Core']
end
