source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/bytedance/cocoapods_sdk_source_repo.git'
source 'https://github.com/volcengine/volcengine-specs.git'

install! 'cocoapods', :deterministic_uuids => false

platform :ios, "8.0"

inhibit_all_warnings!

def ttsdk_pods
  pod 'TTSDK', '1.24.1.2-premium', :subspecs => [
    'Core',
    'TTFFmpeg',
    'PlayerCore',
    'LivePull',
    'LivePush',
    'Player',
    'Image',
    'Uploader',
  ]
end

def common_pods
  pod 'CocoaAsyncSocket', :path => '../Pods-Cache'
  pod 'Masonry'
  pod 'ReactiveObjC'
  pod 'FLEX'
  pod 'Toast', '~> 4.0.0'
  pod 'YYCategories'
  pod 'AFNetworking', '~> 2.0'
  pod 'SDWebImage'
  pod 'MJExtension'
  pod 'IQKeyboardManager'
  pod 'RangersAppLog', '< 6.0.0', :subspecs=>['Core', 'Host']
  pod 'MWPhotoBrowser'
end

target 'TTSDKDemo' do
  ttsdk_pods
  common_pods
end

post_install do |installer|
  system("bash Scripts/update_git_info.sh")
end
